### ISSUE TITLE
SSL+TLS Auth

### ISSUE THREAD

**Issue by and-hom** [diwakergupta/jetcd#9]
Etcd supports ssl/tls authentication. Looks like jetcd does not, does it? 
Retrofit supports working with custom http client impl, so I've just created and tested a local branch with ssl auth support.
Is it a good idea to make a pull request?

**Comment by diwakergupta** [comment]
@and-hom correct, jetcd doesn't support SSL/TLS today. PR is most welcome!

**Comment by and-hom** [comment]
Done

**Comment by diwakergupta** [comment]
You can now pass in arbitrary Retrofit clients into jetcd, thus letting users handle SSL/TLS auth if they want to.
